### ISSUE TITLE
Missing deps building wasmtime_js

### ISSUE THREAD

**Issue by jakob-lilliemarck** [theduke/wasm-javascript#1]
Hi,
I've been checking out you projects to run js in wasm (quickjs-rs, slimjs and this) - awesome work!

In following the instructions at:
https://github.com/theduke/wasm-javascript/tree/main/wasmtime_js my `cargo build` is failing with the message:

```error: no matching package found
searched package name: `witx-bindgen-wasmtime`
perhaps you meant:      wit-bindgen-wasmtime
location searched: https://github.com/bytecodealliance/witx-bindgen
required by package `wasmtime_js v0.1.0 (https://github.com/theduke/wasm-javascript#da6da5f3)`
    ... which satisfies git dependency `wasmtime_js` of package `sbox-wasmtime-js v0.1.0 (/path/to/project)`
```
[https://github.com/bytecodealliance/witx-bindgen](url) redirects to [https://github.com/bytecodealliance/wit-bindgen](url). Looking at the crates directory at [https://github.com/bytecodealliance/wit-bindgen](url) it seems as if several of the crates used by wasmtime_js has changed their package names.

Cloning this repo (theduke/wasm-javascript) and building it strangely works just fine.

**Comment by theduke** [comment]
Yes, this is overdue for a dependency update, there were a few upstream changes.

The checkout works fine because `Cargo.lock` pins the Git tag of the witx dependencies.

ps: I wouldn't say no to a PR, it should mostly just be renaming the packages  I think. ;)

**Comment by theduke** [comment]
I'm working on updating the crate.

**Comment by theduke** [comment]
I did push an update that is functional again.

`cargo run --release --example interop`.

This is bascially just a demo though, `wit-bindgen-cli` does pretty much all of the work.

I really ought to write this up into a blog post.

**Comment by jakob-lilliemarck** [comment]
Amazing, thank you, I'll check it out!
I'd put a PR if I wasn't such a terrible beginner with rust and previously unfamiliar with alot of the deps - thanks for updating and helping out!
